title: "Anna Tselikova"
email: ania.tselikova@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hey! I'm Anna, I'm passionate about building projects :)
  Have a look at my portfolio from MLH Fellowship!
  Also, I'm in love with cats and traveling :)
baseurl: "/" 
url: "/portfolio-template" 
twitter_username: DagnyTaggart17
github_username:  aniats

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg